spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  application:
    name: vector
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example
    driverClassName: org.postgresql.Driver
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org:
      springframework:
        security: INFO
