version: "3"
services:
  postgres:
    image: postgres
    container_name: vector-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - /tmp/vector-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:latest
    container_name: "rabbitmq"
    ports:
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
